Нововведения и небольшие изменения
nggurbanov/applicant-helper pull request #3
Opened 2024-07-22 09:12 UTC by DenisIndenbom

Привет, я добавил пару небольших фичей в бота, а также чуть чуть почистил код

## Что изменилось?
- Бот теперь читает сообщение, на которое ответил пользователь (тоже можно выключить)
- Бот теперь знает, кто ему написал
- Добавил глупый шаблонизатор промтов
- Добавил диалоговый режим (его можно выключить, и мне его убирать из кода)
- Чуть чуть почистил код

Надеюсь ты прочитаешь этот pull request и скажешь, что нужно будет исправить.

P.S: Да, решил написпть на великом могучем языке

2024-07-23 15:17 UTC, DenisIndenbom commented
**_Стартовый комментарий был обновлён._**

# Небольшие изменения и дополнения:
- Бот отвечает тому, кто ответил на его сообщение (тоже можно выключить)
- Бот читает цепочку предыдущих связанных сообщений, используя их для понимание контекста вопроса (тоже можно выключить)
- Улучшил шаблоны
- Исправил костыль в шаблонизаторе
- Привёл код в порядок и добавил немного комментариев/документации
- другие мелочи

P.S: Может, что-то еще добавлю.

2024-07-24 03:26 UTC, nggurbanov requested changes
В целом мне очень понравилось

Хорошо поработал над красотой и читаемостью кода, какие то структурные изменения по большей части тоже на мой взгляд полезные и правильные

Функционал, который ты сам сделал, тоже классный, но надо, конечно, потестить. Еще, я бы поработал над промптами, я скорее всего их сам изменю, у меня просто на мой взгляд достаточно неплохой опыт в "промпт инжиниринге" :)

Какие то штуки мне прям понравилось как ты реализовал, например отвечать пользователю, когда он отвечает на сообщения бота.

Тем не менее, есть ряд нюансов, которые мне кажется нужно исправить + какие то не очень понятные для меня моменты, которые мне бы хотелось, чтобы ты пояснил.

Как то так ;)

2024-07-24 03:26 UTC, nggurbanov commented on underground_info/admins.json
OK

2024-07-24 03:26 UTC, nggurbanov commented on underground_info/group_chat.json
OK

2024-07-24 03:26 UTC, nggurbanov commented on underground_info/mentions.json
OK

2024-07-24 03:26 UTC, nggurbanov commented on config.py
> +SEARCH_MODEL = os.getenv("SEARCH_MODEL")
учитывая изменения которые ты сделал, серч модел лучше сделать так:
"gpt4o-mini" if OPENAI else os.getenv("SEARCH_MODEL")
 или что то в этом духе, ты понял
остальное вроде ок

2024-07-24 03:26 UTC, nggurbanov commented on tools.py
> +async def generate_short(message: str, replies: list, author: str = 'user') -> str:
мне кажется логичнее, если сначала автор будет, потом реплаи (я про порядок аргументов) + ты не установил значение по умолчанию для реплаев

2024-07-24 03:26 UTC, nggurbanov commented on tools.py
> +        response = await generate_short(text, replies, author) if not dialog_mode else await generate_dialog(text)
в генерейт диалог забыл автора

2024-07-24 03:26 UTC, nggurbanov commented on tools.py
> +
вот эт не понял

2024-07-24 03:26 UTC, nggurbanov commented on config.py
> -text = State()
не перенес в артем.ру

2024-07-24 03:26 UTC, nggurbanov commented on artem.py
> +    if message.chat.id == UNDERGROUND_CHAT_ID:
поч?

2024-07-24 03:26 UTC, nggurbanov commented on artem.py
> +        return
зачем?

2024-07-24 03:26 UTC, nggurbanov commented on artem.py
> +        if message.text == "!а" and message.text == "!a":
??

2024-07-24 03:26 UTC, nggurbanov commented on artem.py
> +        if message.text == "!а" and message.text == "!a":
почему and вместо or

2024-07-24 03:30 UTC, nggurbanov commented on tools.py
> +
а или понял, это потому что ты теперь всегда передаешь имя автора сообщения как аргумент и оно никогда не бывает None?

2024-07-24 06:36 UTC, DenisIndenbom commented on tools.py
> +                {"role":"user", "content":message_promt(message, author)}]
Так и думал переделать, если честно

2024-07-24 06:37 UTC, DenisIndenbom commented on artem.py
> +        return
Данная переменная теперь тип int

2024-07-24 06:39 UTC, DenisIndenbom commented on config.py
> -text = State()
Не понимаю, зачем эта переменая

2024-07-24 06:45 UTC, DenisIndenbom commented on artem.py
> +        if message.text == "!а" and message.text == "!a":
Ошибка, исправлю

2024-07-24 06:54 UTC, DenisIndenbom commented on promt_generator.py
Исправлю

2024-07-24 06:58 UTC, DenisIndenbom commented on config.py
> +SEARCH_MODEL = os.getenv("SEARCH_MODEL")
Не вижу особой разницы, можи и там написать

2024-07-24 06:59 UTC, DenisIndenbom commented on tools.py
> +async def generate_short(message: str, replies: list, author: str = 'user') -> str:
Так задумавалось, но можно и так сделать

2024-07-24 07:04 UTC, nggurbanov requested changes

2024-07-24 07:04 UTC, nggurbanov commented on config.py
> +SEARCH_MODEL = os.getenv("SEARCH_MODEL")
разница в том, что если не используется дипинфра, нет смысла в .env указывать модель, потому что в опенаи альтернатив нет и не будет еще очень долго, поэтому это удобнее просто захардкодить

2024-07-24 07:04 UTC, nggurbanov commented on artem.py
> +        return
я имел в виду зачем тут вот эта проверка

2024-07-24 07:08 UTC, DenisIndenbom commented on config.py
> -text = State()
Так переменная всё равно нигде не использовалась, покрайней мере я не вижу, где она использовалась

2024-07-24 07:09 UTC, DenisIndenbom commented on artem.py
> +        return
Чтобы отсейть сообщения не из нашего чата, иначе в контексте могут храниться чужие сообщения. Даже без этого лучше так сделать.

2024-07-24 07:15 UTC, nggurbanov commented on artem.py
> +from aiogram.fsm.context import FSMContext
используется

from aiogram.fsm.state import State #config.py
text = State #config.py
await state.update_data({"text": message.text}) #artem.py

2024-07-24 07:16 UTC, nggurbanov commented on config.py
> -text = State()
ответил в другом комментарии

2024-07-24 07:16 UTC, DenisIndenbom commented on artem.py
> +        return
Я кажись понял, что ты хотел сделать в своём коде. У тебя там баг затаился. Сейчас уберу свою и твою ошибку.

2024-07-24 07:16 UTC, nggurbanov commented on artem.py
> +        return
они ведь и у меня отсеивались
а с твоей имлементацией как будут работать сообщения в личке?

2024-07-24 07:18 UTC, DenisIndenbom commented on artem.py
> +from aiogram.fsm.context import FSMContext
Тебе передаётся данный атрибут в функции `async def chat_message_handler(message: Message, state: FSMContext)`

2024-07-24 07:20 UTC, nggurbanov commented on artem.py
> +from aiogram.fsm.context import FSMContext
<img width="324" alt="Screenshot 2024-07-24 at 11 20 17" src="https://github.com/user-attachments/assets/1482d398-fc5c-44bd-8b49-17697d1aef04">

2024-07-24 07:21 UTC, nggurbanov commented on artem.py
> +        return
>  У тебя там баг затаился. 
расскажи

2024-07-24 07:21 UTC, DenisIndenbom commented on artem.py
> +        return
Я исправил ошибку, читай следующий комит

2024-07-24 07:22 UTC, DenisIndenbom commented on artem.py
> +from aiogram.fsm.context import FSMContext
*тяжёлый вздох*

2024-07-24 07:23 UTC, DenisIndenbom commented on artem.py
> +from aiogram.fsm.context import FSMContext
Это же просто ключ

2024-07-24 07:25 UTC, nggurbanov commented on artem.py
> +from aiogram.fsm.context import FSMContext
state.update_data обновляет данные состояния в FSMContext

я сначала объявляю что в принципе существует состояние text с помощью text = State(), а потом уже через ключ его обновляю

и не надо мне тут писать "тяжелый вздох"

2024-07-24 07:27 UTC, DenisIndenbom commented on artem.py
> +from aiogram.fsm.context import FSMContext
Так, а где ты эту переменую используешь ? (кроме, как её изменяшешь)

2024-07-24 07:28 UTC, DenisIndenbom commented on artem.py
> +from aiogram.fsm.context import FSMContext
`text = data["text"]` Эта строчка?

2024-07-24 07:29 UTC, nggurbanov commented on artem.py
> +from aiogram.fsm.context import FSMContext
<img width="791" alt="Screenshot 2024-07-24 at 11 29 09" src="https://github.com/user-attachments/assets/a6599d14-bff8-4b03-a030-bb7f98f60ae5">

2024-07-24 07:30 UTC, DenisIndenbom commented on artem.py
> +from aiogram.fsm.context import FSMContext
Странно они реализовали, ну ладно....

2024-07-24 07:32 UTC, DenisIndenbom commented on artem.py
> +from aiogram.fsm.context import FSMContext
Исправил, читай следующий комит

2024-07-24 07:32 UTC, DenisIndenbom commented on promt_generator.py
Исправил, читай комит

2024-07-24 07:35 UTC, nggurbanov commented on config.py
не знаю зачем ты переименовал text в text_state но ладно, на работу это не влияет

2024-07-24 07:37 UTC, DenisIndenbom commented on config.py
Просто эта глобальная переменая также названа, как и куча локальных. Это не очень хорошо, поэтому я и переименовал её.

2024-07-24 07:40 UTC, nggurbanov requested changes

2024-07-24 07:40 UTC, nggurbanov commented on artem.py
> +            and CHECK_CHAT_ID:
объясни пожалуйста:
1. почему ты проверяешь что чат не является андеграундом? там разве не == должно быть?
2. что такое чек чат айди и зачем он нужен в принципе

2024-07-24 07:40 UTC, nggurbanov commented on artem.py
> -    await tools.update_underground_context(message.text, name=message.from_user.first_name)
зря убрал апдейт контекста в начале, так правильно было, ты исправил мой код на правильный, а потом снова сделал неправильно)

моя претензия была именно в этой проверке и ретерне, к апдейту контекста вопросов не было, там все верно

2024-07-24 07:40 UTC, nggurbanov commented on artem.py
> +        # await tools.update_underground_context(reply, "Артем Макаров")
вот тут чемп, вот тут я проглядел

2024-07-24 07:42 UTC, DenisIndenbom commented on artem.py
> -    await tools.update_underground_context(message.text, name=message.from_user.first_name)
Ааа, понял) Исправил, жди коммит.

2024-07-24 07:42 UTC, DenisIndenbom commented on artem.py
> +        # await tools.update_underground_context(reply, "Артем Макаров")
Спасибки)

2024-07-24 07:44 UTC, DenisIndenbom commented on artem.py
> +            and CHECK_CHAT_ID:
Объяснения:
1. Да, там ошибка появилась после правки.
2. Это было нужно для отключение этой фичи, но её сейчас просто уберу

2024-07-24 07:47 UTC, nggurbanov commented on config.py
окей

2024-07-24 07:52 UTC, nggurbanov requested changes

2024-07-24 07:55 UTC, DenisIndenbom commented on tools.py
> +
Да, верно. Раньше ты понятно что передавал в `message` (то Message, то str), и поэтому я решил переписать эту часть.

2024-07-24 07:57 UTC, DenisIndenbom commented on tools.py
> +        response = await generate_short(text, replies, author) if not dialog_mode else await generate_dialog(text)
Да, спасибо. Исправил.

2024-07-24 08:00 UTC, nggurbanov commented on tools.py
> +
я воспользовался тем что у питона динамическая типизация и это отлично работало, но да, это ваще не хорошая практика и ты сделал более грамотно

2024-07-24 08:01 UTC, DenisIndenbom reviewed
OK

2024-07-24 08:03 UTC, DenisIndenbom commented on tools.py
> +
Обычно, если так делают, то делают жёсткую проверку типов и пишут отдельные функции для каждого типа, т.к в питоне нет function overload.

2024-07-24 08:05 UTC, nggurbanov approved these changes
Ура.

2024-07-24 08:05 UTC, merged